emotion: True
gray: False
dataset:
  batch: 32
  train_csv : '/data/FaceEmotion/AFFNet/train_set/train_dataset.csv'
  val_csv : '/data/FaceEmotion/AFFNet/val_set/val_dataset.csv'
train:
  model: 'resnet18'
  lr: 0.0001
  epochs: 20
  val_iters: 100
  loss: 'ce'
  optim: 'adamw'
  scheduler: {'MultiStepLR': {"milestones": [5, 10, 15, 20], "gamma": 0.5}}
  logit: False
  mixup: True
